### ISSUE TITLE
click event error 

### ISSUE THREAD

**Issue by powercording** [BioComputingUP/ProSeqViewer#3]
```
selection.model.js:19 Uncaught TypeError: Cannot read properties of undefined (reading 'dataset')
    at SelectionModel.set_start (selection.model.js:19:1)
    at sqv.onmousedown (selection.model.js:56:1)
```
in next js  13.4 app (page router)
when I click sequence then this error shows in console.
you can also see this error msg at the documentation web site - event tap and click it.

**Comment by mb925** [comment]
Hello,
I cant reproduce the issue. Can you please send more details?

What I did was:

- access the Proseqviewer documentation: https://biocomputingup.github.io/ProSeqViewer-documentation/doc
- go to Events > events test section
- right click on the sequence

but nothing appears in the console.

**Comment by freehour** [comment]
I have the same issue using Chrome, it works in Firefox. It happens on left-click. This is the relevant code section where the error occurs: https://github.com/BioComputingUP/ProSeqViewer/blob/3bcadd92532207260ff30bc992c4b36676d53910/src/lib/selection.model.ts#L31

It seems `e.path` is undefined and therefore falsly executing the else block of the condition. I'm unsure what `e.path` should be, however using `element = e.currentTarget` should work in Chrome.
